### PR TITLE
Show implementation

### PR DESCRIPTION
**Pull request by paraynaud**
See issue #28

### CODE REVIEW

**Comment by paraynaud** [comment]
The minimal example
```julia
using PartiallySeparableNLPModels
using ADNLPModels


n = 4
function example(x)
  n = length(x)
  n < 2 && @error("length of x must be >= 2")
return exp(x[1] + x[2]) - exp(x[2] + x[3]+x[4]) + sum((x[i]+x[i+1])^2 for i=1:n-1)
end 
start_example(n :: Int) = ones(n)
example_ADNLPModel(n :: Int) = ADNLPModel(example, start_example(n), name="Example " * string(n) * " variables")

x = ones(n)
nlp = example_ADNLPModel(n)
pbfgsnlp = PartiallySeparableNLPModel(nlp; name = :pbfgs)
```
returns 
```
ADNLPModel - Model with automatic differentiation backend ADNLPModels.ForwardDiffAD{ForwardDiff.GradientConfig{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4, Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4}}}}(10, 0, ForwardDiff.GradientConfig{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4, Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4}}}((Partials(1.0, 0.0, 0.0, 0.0), Partials(0.0, 1.0, 0.0, 0.0), Partials(0.0, 0.0, 1.0, 0.0), Partials(0.0, 0.0, 0.0, 1.0)), ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, 
Float64, 4}[Dual{ForwardDiff.Tag{typeof(example), Float64}}(5.0e-324,1.0e-323,1.5e-323,2.0e-323,2.5e-323), Dual{ForwardDiff.Tag{typeof(example), Float64}}(3.0e-323,3.5e-323,4.0e-323,4.4e-323,5.0e-323), Dual{ForwardDiff.Tag{typeof(example), 
Float64}}(5.4e-323,6.0e-323,6.4e-323,NaN,7.4e-323), Dual{ForwardDiff.Tag{typeof(example), Float64}}(8.0e-323,8.4e-323,9.0e-323,9.4e-323,NaN)]))
  Problem name: Example 4 variables
   All variables: ████████████████████ 4      All constraints: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            free: ████████████████████ 4                 free: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
         low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0              low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
          infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            nnzh: (  0.00% sparsity)   10              linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
                                                    nonlinear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
                                                         nnzj: (------% sparsity)

  Counters:
             obj: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 grad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 cons: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            jcon: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                jgrad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                  jac: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           jprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               jtprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 hess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           hprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                jhess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               jhprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
Partitioned structure summary:
5 element  functions; represented by 3 expression trees.
Among element functions:
 - 0 is linear;
 - 3 are quadratic;
 - 0 is cubic;
 - 2 are general;
and:
 - 4 are convex;
 - 1 is concave;
 - 0 is more general.
Each element affect 2 ≤ 2.2 (mean) ≤ 3 elements.
Each problem variable is affected by 2 ≤ 2.75 (mean) ≤ 4 elements
```

**Comment by dpo** [comment]
Those are interesting statistics! It would be great to display them the same way as the rest of the meta information on the NLPModel.

**Comment by paraynaud** [comment]
Now the results is:
```julia
ADNLPModel - Model with automatic differentiation backend ADNLPModels.ForwardDiffAD{ForwardDiff.GradientConfig{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4, Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4}}}}(10, 0, ForwardDiff.GradientConfig{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4, Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, Float64, 4}}}((Partials(1.0, 0.0, 0.0, 0.0), Partials(0.0, 1.0, 0.0, 0.0), Partials(0.0, 0.0, 1.0, 0.0), Partials(0.0, 0.0, 0.0, 1.0)), ForwardDiff.Dual{ForwardDiff.Tag{typeof(example), Float64}, 
Float64, 4}[Dual{ForwardDiff.Tag{typeof(example), Float64}}(1.07395097e-315,1.073951127e-315,1.073951443e-315,1.0739516e-315,1.07395176e-315), Dual{ForwardDiff.Tag{typeof(example), Float64}}(1.073951917e-315,1.073952075e-315,1.07395239e-315,1.07395255e-315,1.07395271e-315), Dual{ForwardDiff.Tag{typeof(example), Float64}}(1.073952866e-315,1.07395318e-315,1.07395334e-315,1.0739535e-315,1.073953656e-315), Dual{ForwardDiff.Tag{typeof(example), Float64}}(1.073953814e-315,1.07395413e-315,1.07395429e-315,1.07395761e-315,1.23354832e-315)]))
  Problem name: Example 4 variables
   All variables: ████████████████████ 4      All constraints: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            free: ████████████████████ 4                 free: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                lower: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                upper: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
         low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0              low/upp: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                fixed: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
          infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               infeas: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            nnzh: (  0.00% sparsity)   10              linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
                                                    nonlinear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
                                                         nnzj: (------% sparsity)

  Counters:
             obj: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 grad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 cons: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
            jcon: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                jgrad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                  jac: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           jprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               jtprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 hess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           hprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                jhess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               jhprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0

Partitioned structure summary:
               N: ███████████████⋅⋅⋅⋅⋅ 3
               n: ████████████████████ 4
               M: █████⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 1
   Element statistics:
          linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               convex: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
       quadratic: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0              concave: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           cubic: ████████████████████ 3              general: ████████████████████ 3
         general: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                     : ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
  Element function dimensions:                     Variable overlappings:
             min: ████████████████████ 2.0                min: ██████████⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 1.0
           mean:: ████████████████████ 2.0              mean:: ███████████████⋅⋅⋅⋅⋅ 1.5
             max: ████████████████████ 2.0                max: ████████████████████ 2.0
```
In the terminal, they are aligned. I used `NLPModels.lines_of_hist` to make it.

**Comment by dpo** [comment]
Thank you, that looks a lot better!!!

A few comments:
* it's not clear to me what N, n, and M represent;
* under "general" in the top right, there's an empty category;
* "overlappings" → "overlaps".

**Comment by paraynaud** [comment]
> - under "general" in the top right, there's an empty category;

I implemented the two columns (Element statistics) with:
```julia
S1 = ["linear", "quadratic", "cubic", "general"]
V1 = [linear, quadratic, cubic, general]
LH1 = NLPModels.lines_of_hist(S1, V1)

S2 = ["convex", "concave", "general", " "]
V2 = [convex, concave, general, 0 ]
LH2 = NLPModels.lines_of_hist(S2, V2)

LH = map((i,j) -> i*j, LH1, LH2)
print(io, join(LH, "\n"))
```
i wanted an easy `map`.
I changed it to :
```julia
S2 = ["convex", "concave", "general"]
V2 = [convex, concave, general ]
LH2 = NLPModels.lines_of_hist(S2, V2)

LH = map((i) -> LH1[i]*LH2[i], 1:3)
push!(LH, LH1[4])
print(io, join(LH, "\n"))
```
now we have, the 
```julia
Partitioned structure summary:
         N (element functions): ███████████████⋅⋅⋅⋅⋅ 3
               n (problem's size): ████████████████████ 4
M (distinct element functions): █████⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 1
   Element statistics:
             linear: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0            convex: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
       quadratic: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0          concave: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
           cubic: ████████████████████ 3              general: ████████████████████ 3
         general: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
  Element function dimensions:                         Variable overlaps:
             min: ████████████████████ 2.0                 min: ██████████⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 1.0   
           mean: ████████████████████ 2.0              mean: ███████████████⋅⋅⋅⋅⋅ 1.5
             max: ████████████████████ 2.0                max: ████████████████████ 2.0
```

**Comment by dpo** [comment]
Ok, thank you. That's better, but

* the alignment is off;
* I don't think it's useful to call things N, n or M; just say "number of element functions", and
    * there is no need to repeat the total number of variables;
    * I don't see the difference between N and M.

**Comment by paraynaud** [comment]
> the alignment is off;

only when I copy paste the code, it is aligned in the terminal.

M count the number of distinct element functions after the translation to elemental variables.
For example:

$$
f(x) = \sum_{i=1}^N g(x_i, x_{i+1}),
$$

N may vary, but M=1 because every element function is the same function $g$ parametrized by different variables.

**Comment by dpo** [comment]
Ok, let's just remove `n` (it's already stated above), and remove the names `N` and `M` to only leave the descriptions.

**Review by dpo — APPROVED** [review]

**Pull request merged**
