### PR TITLE
Fix the default type from original NLPModel

### PR DESCRIPTION
**Pull request by paraynaud**

### CODE REVIEW

**Review by tmigot — CHANGES_REQUESTED** [review]
Could you use
```
SupportedNLPModel{T, S} = Union{ADNLPModel{T, S}, MathOptNLPModel{T, S}}
```
so that you could use the parametric type instead of doing an `eltype`?

**Comment by paraynaud** [comment]
> Could you use
> 
> ```
> SupportedNLPModel{T, S} = Union{ADNLPModel{T, S}, MathOptNLPModel{T, S}}
> ```
> 
> so that you could use the parametric type instead of doing an `eltype`?

That sounds reasonable, but we cannot change `T` from the `SupportedNLPModel{T, S}` used.
I am not fan of it.

I will left this PR on stand-by for now.
I plan to implement different backends to compute the partitioned gradient.
Depending on the backend used, `T` may change.
Thanks for your review!

**Comment by paraynaud** [comment]
> I am not sure to understand the issue. You could still change it if a different `type` is given in the keyword argument, no?

Sorry, I didn't catch directly what you suggested. 
You're right, something like:
```julia
PartitionedModel(nlp::SupportedNLPModel{T,S}; type::DataType = T, ...) where {T,S}
```
should work fine!

**Comment by paraynaud** [comment]
hi @tmigot , about
> SupportedNLPModel{T, S} = Union{ADNLPModel{T, S}, MathOptNLPModel{T, S}}

I checked [`MathOptNLPModel`](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/1c96e8bf6032368acfefc30443bf080aae755db8/src/moi_nlp_model.jl#L3):
```julia
mutable struct MathOptNLPModel <: AbstractNLPModel{Float64, Vector{Float64}}
```
there is no `T,S` parameter in the conrete type.
As a negative consequence for me, the code
```julia
PartitionedModel(nlp::SupportedNLPModel{T,S}; type::DataType = T, ...) where {T,S}
```
can't work if `nlp` is a `MathOptNLPModel `, because `T` will not be defined (as well as `S`).

I am currently working on the derivatives backends, I will provide a solution at that time.

**Pull request closed without merging**
