### PR TITLE
Bump to NLPModels 0.18

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by paraynaud** [comment]
Do you plan to add the 0.19 when the tests succeed?

**Comment by tmigot** [comment]
Actually, it doesn't work yet because when looking at the logs form GithubAction it still uses NLPModels 0.17.
I think the problem comes from the fact that NLPModels 0.18 is compatible with NLPModelsJuMP 0.9 and 0.10, and NLPModels JuMP >= 0.9 is only compatible with JuMP 0.22.

**Comment by tmigot** [comment]
> Do you plan to add the 0.19 when the tests succeed?

The idea was to add NLPModels 0.19 in a separate PR

**Comment by paraynaud** [comment]
I just added the work I did the last days, I removed the JuMP dependecy of the module.
It should ease your problem.

**Comment by tmigot** [comment]
Argh! I don't think it's an emergency. Maybe, we should move this PR to a draft for the record and create issues in this package and in ExpressionTreeForge. What do you think?

**Comment by paraynaud** [comment]
> Argh! I don't think it's an emergency. Maybe, we should move this PR to a draft for the record and create issues in this package and in ExpressionTreeForge. What do you think?

I agree.
ExpressionTreeForge.jl dependencies impact all my modules.
It uses an old version of ModelingToolKit (v3.20.1) to generate expression trees from an ADNLPModel, which prevents several packages to be upgrade (including JuMP).
I plan to get rid of ModelingToolKit in the future, but I must find an alternative to support the ADNLPModels.

**Comment by tmigot** [comment]
The issues are there. Bon courage!

**Comment by paraynaud** [comment]
see #57

**Comment by tmigot** [comment]
Superseded by #57 . Good job @paraynaud !

**Pull request closed without merging**
